# yaml-language-server: $schema=https://coderabbit.ai/coderabbit-schema.v2.json
version: "2"
language: "en-US"
reviews:
  profile: "chill"
  auto_review:
    enabled: true
    base_branches:
      - main
      - develop
      - staging